--Create the tables for the value generation system
create table KEY_VALUE_INDICATORS (
    INDICATOR_ID INT primary key,
    INDICATOR_NAME VARCHAR(255) not null,
    DATE_INDICATOR_ADDED DATE not null,
    DATE_INDICATOR_REMOVED DATE
);
create table KEY_VALUE_INDICATOR_LEAD (
    INDICATOR_ID INT,
    LEAD_FOR_INDICATOR_ID INT,
    DATE_ADDED_AS_LEAD DATE not null,
    DATE_REMOVED_AS_LEAD DATE,
    constraint FK_LEAD_INDICATOR_ID foreign key (INDICATOR_ID) references KEY_VALUE_INDICATORS (INDICATOR_ID),
    constraint FK_LEAD_FOR_INDICATOR_ID foreign key (LEAD_FOR_INDICATOR_ID) references KEY_VALUE_INDICATORS (INDICATOR_ID)
);
create table KEY_VALUE_INDICATOR_LAG (
    INDICATOR_ID INT,
    LAG_FOR_INDICATOR_ID INT,
    DATE_ADDED_AS_LAG DATE not null,
    DATE_REMOVED_AS_LAG DATE,
    constraint FK_LAG_INDICATOR_ID foreign key (INDICATOR_ID) references KEY_VALUE_INDICATORS (INDICATOR_ID),
    constraint FK_LAG_FOR_INDICATOR_ID foreign key (LAG_FOR_INDICATOR_ID) references KEY_VALUE_INDICATORS (INDICATOR_ID)
);
create table KEY_VALUE_INDICATOR_TARGET_VALUES (
    INDICATOR_ID INT,
    TARGET_VALUE VARCHAR2(255) not null,
    DATE_TARGET_VALUE_START DATE not null,
    DATE_TARGET_VALUE_END DATE,
    THRESHOLD_VALUE_FOR_RAG VARCHAR2(255) not null,
    constraint FK_TARGET_INDICATOR_ID foreign key (INDICATOR_ID) references KEY_VALUE_INDICATORS (INDICATOR_ID)
);
create table KEY_VALUE_INDICATOR_PRIORITY (
    INDICATOR_ID INT,
    INDICATOR_PRIORITY INT not null,
    DATE_PRIORITY_START DATE not null,
    DATE_PRIORITY_END DATE,
    constraint FK_PRIORITY_INDICATOR_ID foreign key (INDICATOR_ID) references KEY_VALUE_INDICATORS (INDICATOR_ID)
);
create table VALUE_GENERATING_PROGRAMS (
    PROGRAM_ID INT primary key,
    PROGRAM_NAME VARCHAR2(255) not null,
    PROGRAM_OWNER VARCHAR2(255) not null,
    DATE_PROGRAM_ADDED DATE,
    DATE_PROGRAM_REMOVED DATE
);
create table VALUE_GENERATING_INITIATIVES (
    INITIATIVE_ID INT primary key,
    INITIATIVE_NAME VARCHAR2(255) not null,
    INITIATIVE_OWNER VARCHAR2(255) not null,
    DATE_INITIATIVE_ADDED DATE,
    DATE_INITIATIVE_REMOVED DATE,
    PROGRAM_ID NUMBER,
    constraint FK_PROGRAM_ID foreign key (PROGRAM_ID) references VALUE_GENERATING_PROGRAMS (PROGRAM_ID)
);
create table KEY_VALUE_INDICATOR_ACTUALS (
    INDICATOR_ID INT,
    INITIATIVE_ID INT,
    ACTUAL_VALUE VARCHAR2(255) not null,
    IS_PROMISED_VALUE BOOLEAN not null default 0, -- 0 = false, 1 = true. Default to measured unless in future
    DATE_VALUE_EFFECTIVE DATE not null,
    ACTUAL_VALUE_SOURCE VARCHAR2(255) not null default 'promised',
    constraint FK_ACTUALS_INDICATOR_ID foreign key (INDICATOR_ID) references KEY_VALUE_INDICATORS (INDICATOR_ID),
    constraint FK_ACTUALS_INITIATIVE_ID foreign key (INITIATIVE_ID) references VALUE_GENERATING_INITIATIVES (INITIATIVE_ID)
);